name: Notify QA PR
on:
  pull_request:
    branches: [qa]
    types: [opened, edited]
jobs:
  notify-qa-pr-channel:
    runs-on: ubuntu-latest
    steps:
      - name: Notify MS Teams channel
        uses: dhollerbach/actions.send-message-to-ms-teams@1.0.10
        if: github.head_ref != 'master' && github.head_ref != 'main' # don't run if it's merging from master or main back to qa
        with:
          webhook: ${{ secrets.MS_TEAMS_WEBHOOK_QA_PR }}
          message:
            '[${{ github.event.pull_request.html_url }}](${{ github.event.pull_request.html_url }}): ${{
            github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}'
